### ISSUE TITLE
Страницы не открываются в новых вкладках

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#1]
Если кликнуть по любой ссылке таким способом: Ctrl+ЛКМ, то новая вкладка не открывается, а клик перехватывается и подгружается контент.

А я хочу просто открывать много вкладок!

**Comment by andreymal** [comment]
СКМ намного удобнее, купи себе мышку с колёсиком-кнопкой :D

Fixed by https://github.com/andreymal/mini_fiction/commit/f7754136523a49e8cb0a0176aaa08bc03efc045e

**Comment by fox0** [comment]
Спасибо большое
