### ISSUE TITLE
Не открываются внешние ссылки на сайте

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#2]
Ничего не происходит, если кликнуть по ссылке, ведущей на внешний сайт. Примет такой ссылки: https://ficbook.net/

**Comment by andreymal** [comment]
Не воспроизводится, у меня всё происходит и с ЛКМ, и с Ctrl+ЛКМ, и с СКМ. Какая ссылка и какой браузер?

**Comment by fox0** [comment]
Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0

https://hkar.ru/PWME

**Comment by andreymal** [comment]
Хз, в моём Firefox 54 она прекрасно открывается любыми способами, и выделенный на скриншоте return как раз возвращает управление браузеру, чтобы он самостоятельно открыл эту ссылку)

**Comment by fox0** [comment]
Одно из дополнений браузера тоже навешивает событие click на ссылки. И что-то не срослось. Закрыто.

**Comment by andreymal** [comment]
А какое дополнение-то? Вдруг это всё-таки моя проблема и я смогу починить, а даже если не смогу, то для меня важно знать об имеющихся проблемах, потому что AJAX я буду использовать не только на этом сайте

**Comment by fox0** [comment]
Хм... Это не то дополнение, на которое я подумал. Путь до скрипта: resource://gre/modules/RemoteAddonsParent.jsm
