### ISSUE TITLE
[Запрос фичи] Отключение AJAX-подгрузки страницы

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#3]
Дать возможность пользователю отключить часть функционала сайта.

**Comment by andreymal** [comment]
Может лучше я его просто починю?)

**Comment by fox0** [comment]
Как хочешь, отключить js насовсем никогда не поздно)

**Comment by andreymal** [comment]
Вообще возможность дам (я думал, она и так есть, а оказывается в этом сайте сделать забыл), но не в интерфейсе, ибо нефиг

**Comment by andreymal** [comment]
Fixed by https://github.com/andreymal/mini_fiction/commit/0090b9d501bba44972d709c0b81a7376e4bbc1a4

Кнопочки нет и не будет, можно добавить печеньку `noajax=1` любым удобным способом (в настройках, если браузер позволяет) или вписав в JS-консоль что-нибудь такое

```javascript
document.cookie = 'noajax=1; path=/; expires=Thu, 31 Dec 2099 23:59:59 GMT;Cache-Control: must-revalidate, s-maxage=0, max-age=0';
```
