### ISSUE TITLE
Кривая сортировка рассказов на странице /accounts/<id>/

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#4]
Поменена сортировка рассказов, по сравнению с оригинальным сториесом, однако рассказы в черновиках продолжают отображаться в самом низу.

**Comment by andreymal** [comment]
Новые вверху, старые внизу, черновики ниже всех. Так задумано. Не кривая это какая?

**Comment by fox0** [comment]
Логично предположить, что все новые рассказы (в черновиках или нет) будут вверху.

**Comment by andreymal** [comment]
Fixed by https://github.com/andreymal/mini_fiction/commit/89a1aebc998c3b009ffb75324ba97a2fa2ae05c9
