### ISSUE TITLE
The CSRF session token is missing. Сервер не устанавливает куки

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#5]
Идентификатор сборки: Mozilla/5.0 (X11; Linux i686; rv:58.0) Gecko/20100101 Firefox/58.0

1) от сервера приходит сессионная кука, но! Для домена .ponyfiction.org; HttpOnly; Сайт работает https://ponyfiction.org/ на другом (возможно) домене и по https. Из-за этого браузер игнорит куку и не принимает её.
2) Понятия не имею где должно быть "CSRF session token", в куках или где, но ни сброс пароля https://ponyfiction.org/accounts/password/reset/ ни логин https://ponyfiction.org/accounts/login/ не работает. Логи:

POST https://ponyfiction.org/accounts/password/reset/
Host: ponyfiction.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: application/json,*/*
Accept-Encoding: gzip, deflate, br
Referer: https://ponyfiction.org/accounts/password/reset/
content-type: multipart/form-data; boundary=---------------------------13341289461704719559697187966
x-ajax: 1
x-csrftoken: [вырезано]
origin: https://ponyfiction.org
Content-Length: 392
DNT: 1
Connection: keep-alive

-----------------------------13341289461704719559697187966
Content-Disposition: form-data; name="csrf_token"

[вырезано]
-----------------------------13341289461704719559697187966
Content-Disposition: form-data; name="email"

[вырезано]@ya.ru
-----------------------------13341289461704719559697187966--

И ответ сервера:
400 Bad Request HTTP/2.0
server: nginx
date: Sat, 03 Mar 2018 14:00:55 GMT
content-type: text/html
content-length: 150
cache-control: max-age=0
vary: X-AJAX
X-Firefox-Spdy: h2

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF session token is missing.</p>

**Comment by andreymal** [comment]
Чёртов гитхаб, не уведомляет о новых issue -_-

Но теперь я наконец заметил и гляну

**Comment by andreymal** [comment]
Ну и да, имей в виду, что ты единственный на всём свете с такой проблемой. Я даже JS в фаерфоксе отключил — всё равно всё нормально работает

**Comment by fox0** [comment]
Да пофиг уже. Пробовал в другом браузере, всё равно не смог войти, пишет нет такого email и неверный логин/пароль.

Но для кук в домене ".ponyfiction.org" точка в начале лишняя.

Закрывай issue, у тебя есть другие пользователи.

**Comment by andreymal** [comment]
Согласно RFC 6265 точка в начале должна игнорироваться (что все нормальные браузеры и делают, кроме почему-то твоего)

**Comment by andreymal** [comment]
>пишет нет такого email

Значит, видимо, email отличался от такового на stories.everypony.ru и при слиянии сайтов заменился, логин бы сказал что ли

**Comment by fox0** [comment]
Синтаксис Set-Cookie https://tools.ietf.org/html/rfc6265#page-9 ссылается на RFC 1034, что довольно логично. А там https://tools.ietf.org/html/rfc1034#section-3.5 синтаксис не разрешает точку а начале домена.

Логин: [вырезано]

**Comment by andreymal** [comment]
Читай секцию 4.1.2.3 в том же https://tools.ietf.org/html/rfc6265

Впрочем, добавление точки я убрал (Flask баганутая хрень, лучше отправить багрепорт туда). Если и сейчас будет The CSRF session token is missing, то это абсолютно точно проблемы именно твоего браузера или одного из жуть каких параноидальных расширений.

А у [вырезанного, лол] стоит-таки какая-то @ya.ru почта, и я сейчас успешно запросил туда восстановление пароля из фаерфокса с отключенным джаваскриптом.

**Comment by fox0** [comment]
Что-то секции 4.1.2.3 не вижу. Спасибо, письмо пришло (но не на ту почту, которая была на сториесе, видимо два аккаунта смерджились).

**Comment by andreymal** [comment]
У тебя браузер настолько параноидальный, что целые секции из RFC вырезает? :D https://i.imgur.com/vltad4V.png

Но точку я всё равно убрал, так как «that character is not permitted»

**Comment by fox0** [comment]
Так сказать, чтобы защитить пользователя даже от чтения спецификаций кук :D 
Нашёл: https://tools.ietf.org/html/rfc6265#page-11

**Comment by andreymal** [comment]
ValueError: Value -9999999999999999999999999999 of attr Author.comment_spoiler_threshold is less than the minimum allowed value -32768

Вот тебе делать нечего :D

**Comment by fox0** [comment]
Но мне было скучно

**Comment by andreymal** [comment]
А вообще, судя по успешному логину, issue можно закрывать

**Comment by andreymal** [comment]
С обновлением до Flask 1.0 стало возможно выпилить домен вообще

https://github.com/andreymal/mini_fiction/commit/a6c12749de9e1ad7e5460f5ed23cdc7b5aa95954#diff-ec9ab3b67cf6f01a2a1003b61d92b9eeR92
