### ISSUE TITLE
[опечатка] NC-18 - нет такого рейтинга

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#6]
В справке https://ponyfiction.org/page/help/classifications/ и в базе написано NC-18. Нет такого рейтинга, а есть NC-17 (no children under 17).

Ещё есть NC-21, но не будем о нём.

**Comment by andreymal** [comment]
«Рейтинг – неформальная система определений», так что хоть NC-99 от балды написать можно )

**Comment by fox0** [comment]
[Рейтинговая система MPAA](https://ru.wikipedia.org/w/index.php?oldid=86945046) не просто так придумана.

**Comment by andreymal** [comment]
А на сайте применяется не она.

**Comment by fox0** [comment]
Тебя не переспоришь, закрывай issue.

**Comment by andreymal** [comment]
Куда спешить, вдруг я надумаю накатить именно рейтинговую систему MPAA :)

**Comment by andreymal** [comment]
Теперь на сайте рейтинговая система MPAA.
