### ISSUE TITLE
MultipleObjectsFoundError: Multiple objects were found. Use StoryView.select(...) to retrieve them

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#7]
Если я залогинен, но [этот урл](https://ponyfiction.org/story/12767/) не открывается с 500 ошибкой.

**Comment by andreymal** [comment]
Fixed by https://github.com/andreymal/mini_fiction/commit/3f082418b84945b107ebdd79505b1d84cdeba5e3
