### ISSUE TITLE
The CSRF token has expired в комментариях.

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#8]
Если открыть рассказ, долго-долго его читать, а потом проголосовать за комментарий (/story/<story_id>/comment/<comment_id>/vote/), то вылезает красная всплывашка с сообщением, что не может распарсить json.

**Comment by andreymal** [comment]
Заменил всплывашку на другую всплывашку и увеличил срок годности токена до недели — у кого вкладка открыта ещё дольше, это уже их личные проблемы

https://github.com/andreymal/mini_fiction/commit/65b42a6811e2a3aae2f5cc257bc5a9227991be83

https://github.com/andreymal/mini_fiction/commit/cd50fb6d41120f4a66211fe3315e2a0dd4a086a7
