### ISSUE TITLE
AJAX не работает в пагинаторе

### ISSUE THREAD

**Issue by fox0** [andreymal/ponyfiction.org#9]
Например, [здесь](https://ponyfiction.org/search/character/89/) если нажать на вторую страницу, то страница откроется, как обычно, а клик не будет перехвачен.

**Comment by andreymal** [comment]
Мог бы ещё обратить внимание, что сама форма тоже без аякса работает. Когда-то давно он был кривой и не работал, и я его отключил, а потом воткнул починяющие костыли, а включить назад забыл.

https://github.com/andreymal/mini_fiction/commit/ad96f9e7fc5d91ef98d7d489d2a7fa9dcfa92d45
